# Generated by Django 4.2.2 on 2023-06-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=250, verbose_name="To'liq Ism ")),
                ('username', models.CharField(max_length=250, null=True, verbose_name='Username')),
                ('telegram_id', models.BigIntegerField(default=1, unique=True, verbose_name='Telegram Id')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uzb_word', models.CharField(max_length=300)),
                ('eng_word', models.CharField(max_length=300)),
            ],
        ),
    ]
